#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

./Allclean

touch case.foam

runApplication fluentMeshToFoam fluent.msh

# Create faceZones for baffles and fan
runApplication topoSet

# Create wall and cyclic baffles and the fields on them
runApplication createBaffles -overwrite

runApplication createPatch -overwrite

cp -r 0.orig 0

runApplication simpleFoam

