#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#awk '/^Time/{printf $3 " "};/^d32/{print $3}' logEQMOM > d32EQMOM
#awk '{a[NR]=$0;if(/Execution/)print a[NR-1]}' logQMOM > d32QMOM

graphName="U.eps"

gnuplot<<EOF

set terminal postscript eps color enhanced font "Arial, 20" 
set output "$graphName"
set grid
set border linewidth 2

#set title "Case 3" 
#set key box
#set logscale y

set xlabel "Time (s)" 
set ylabel "Horizental liquid velocity (m/s)" 

set key top right spacing 2 samplen 1 font "Arial, 15" 

set size 0.7, 0.6
set xrange [0:100]
set yrange [-0.5:0.5]

plot "../postProcessing/probesDict/0/U.waterx" using 1:2 title "" with lines lw 3 lc rgb "black", \
     "../postProcessing/probesDict/0/U.waterx" using 1:3 title "" with lines lw 3 lc rgb "blue"

         
EOF


graphName="alpha.eps"

gnuplot<<EOF

set terminal postscript eps color enhanced font "Arial, 20" 
set output "$graphName"
set grid
set border linewidth 2

#set title "Case 3" 
#set key box
#set logscale y

set xlabel "Time (s)" 
set ylabel "Phase fraction (-)" 

set key top right spacing 2 samplen 1 font "Arial, 15" 

set size 0.7, 0.6
set xrange [0:0.2]
set yrange [0:0.08]

plot "../postProcessing/sampleDict/100/y0.2.xy" using 1:2 title "" with lines lw 4 lc rgb "black"
         
EOF



# ----------------------------------------------------------------- end-of-file
