#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

foamCleanTutorials

runApplication fluent3DMeshToFoam fluent.msh
runApplication denseParticleFoam
runApplication postProcess -funcs '(components(U.water))'
rm log.postProcess
runApplication postProcess -func probesDict
rm log.postProcess
runApplication postProcess -func sampleDict -latestTime
rm log.postProcess

./DATA/post


#------------------------------------------------------------------------------
