#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
# Set application name


foamCleanTutorials
touch case.foam

runApplication blockMesh
runApplication simpleFoam
runApplication postProcess -func sampleDict -latestTime
./data/makeGraph

