#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean

touch case.foam

cp -r 0.orig 0/

runApplication blockMesh
#runApplication bubblyDPMFoam
runApplication DPMFoam



#------------------------------------------------------------------------------
